version: '3'
services:
  client:
    image: "codiemullins/multi-client"
    mem_limit: 512m
    hostname: client
  server:
   image: "codiemullins/multi-server"
   mem_limit: 512m
   hostname: api
   environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      PGUSER: $PGUSER
      PGHOST: $PGHOST
      PGDATABASE: $PGDATABASE
      PGPASSWORD: $PGPASSWORD
      PGPORT: $PGPORT
  worker:
    image: "codiemullins/multi-worker"
    mem_limit: 512m
    hostname: worker
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
  nginx:
    image: "codiemullins/multi-nginx"
    mem_limit: 512m
    hostname: nginx
    ports:
      - "80:80"
